### ISSUE TITLE
关于序号乱序和内容排版上的建议

### ISSUE THREAD

**Issue by 2951121599** [datawhalechina/faster-git#19]
第六章-GitFlow工作流实战-关于序号乱序和内容排版上的建议
<img width="986" alt="Snipaste_2022-05-22_11-13-59" src="https://user-images.githubusercontent.com/37405850/169676699-8934887d-823c-4d64-8f85-814e468dbd51.png">

**Comment by libihan** [comment]
感谢反馈。之前各章节调成统一格式把序号搞错了

Fixed commit：https://github.com/datawhalechina/faster-git/commit/53e59f560aaea09ff8abde955e5ea97e75438324
当前内容：https://github.com/datawhalechina/faster-git/blob/main/lecture06/README.md

**Comment by 2951121599** [comment]
ok, thanks
