### ISSUE TITLE
关于第七节文章的建议

### ISSUE THREAD

**Issue by YasuoSkywalker** [datawhalechina/faster-git#20]
1.第七节中的第一张图片 （git commit）无法正常显示。使用科学上网后仍然无法显示。
![捕获2](https://user-images.githubusercontent.com/91738819/169762556-0b025ca0-a6ea-43ec-952c-28c725bc0e05.PNG)

2.自动化校验commit message中未找到post-commit，可能是post-update
![捕获2](https://user-images.githubusercontent.com/91738819/169762864-1afe7718-de8c-4546-90bb-aab2fbf573b1.PNG)

**Comment by 2951121599** [comment]
涉及提交的commit, 的确是这四个, 可以参考下此图[Git Hooks](https://img-blog.csdnimg.cn/9ef8d74a0c0c4e17a30840b1677c087e.png) @YasuoSkywalker

**Comment by YasuoSkywalker** [comment]
> 涉及提交的commit, 的确是这四个, 可以参考下此图[Git Hooks](https://img-blog.csdnimg.cn/9ef8d74a0c0c4e17a30840b1677c087e.png) @YasuoSkywalker

好的，谢谢大佬！
